/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
    kotlin("plugin.serialization") version "2.1.20" // ✅ Required!
    id("com.google.devtools.ksp") version "2.0.0-1.0.21"


    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven { url = uri("https://maven.restate.dev/releases") }
}

dependencies {
    // Logger
    implementation("ch.qos.logback:logback-classic:1.4.11") // or latest version
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.3") // or latest


    // Ktor
    implementation("io.ktor:ktor-server-core:2.3.6")
    implementation("io.ktor:ktor-server-netty:2.3.6")
    implementation("io.ktor:ktor-server-content-negotiation:2.3.6")
    implementation("io.ktor:ktor-serialization-kotlinx-json:2.3.6")

    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")

    // Koin for DI
//    implementation("io.insert-koin:koin-ktor:3.4.3")
    implementation("io.insert-koin:koin-ktor:3.5.0")


    // Database (e.g. Exposed + PostgreSQL)
    implementation("org.jetbrains.exposed:exposed-core:0.45.0")
    implementation("org.jetbrains.exposed:exposed-dao:0.45.0")
    implementation("org.jetbrains.exposed:exposed-jdbc:0.45.0")
    implementation("org.postgresql:postgresql:42.7.1")

    // HikariCP for connection pooling
    implementation("com.zaxxer:HikariCP:5.1.0")
    // Restate
    ksp("dev.restate:sdk-api-kotlin-gen:2.0.0")
    annotationProcessor("dev.restate:sdk-api-gen:2.0.0")
    implementation("dev.restate:sdk-kotlin-http:2.0.0")

    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation("io.kotest:kotest-runner-junit5:5.7.2")
    testImplementation("io.ktor:ktor-server-tests:2.3.4")

    // This dependency is used by the application.
    implementation(libs.guava)
}

configurations.all {
    resolutionStrategy.eachDependency {
        if (requested.group == "org.jetbrains.kotlinx" && requested.name.startsWith("kotlinx-coroutines")) {
            useVersion("1.7.3")
            because("Ensure all coroutines modules use the same version to avoid NoSuchMethodError")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.shakirfattani.AppKt"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
