/*
 * This source file was generated by the Gradle 'init' task
 */
package org.shakirfattani

import io.ktor.server.engine.*
import io.ktor.server.netty.*
import io.ktor.server.application.*
import io.ktor.server.response.*
import io.ktor.server.request.*
import io.ktor.server.routing.*
import io.ktor.server.plugins.contentnegotiation.*
import io.ktor.serialization.kotlinx.json.*
import org.koin.ktor.ext.inject
import org.koin.ktor.plugin.Koin
import kotlinx.serialization.Serializable

fun main() {
    println("Starting Application.......")
    embeddedServer(Netty, port = 8080, module = Application::module).start(wait = true)
}

fun Application.module() {
    install(ContentNegotiation) {
        json()
    }

    install(Koin) {
    }

    routing {
        get("/") {
            call.respondText("Hello, Ktor with Koin!")
        }
    }
}
